### ISSUE TITLE
parameter mistake in pixel norm

### ISSUE THREAD

**Issue by DanielCho-HK** [ziwei-jiang/PGGAN-PyTorch#2]
Hi author, i think whether there is a parameter mistake in line29 of utils.py
10e-8 should be changed to 1e-8, according to the original paper.

**Comment by ziwei-jiang** [comment]
Hi Daniel, Apologies for the delayed response. You are correct that the epsilon is 1e-8 in the original paper. However, I believe this shouldn't impact the model's performance as it is just used to prevent division by zero. Nevertheless, I appreciate your diligence in identifying this.
