### ISSUE TITLE
utils中的Pixel_norm

### ISSUE THREAD

**Issue by 1749352011** [ziwei-jiang/PGGAN-PyTorch#3]
utils中的Pixel_norm函数中的sum函数应该改为mean函数才符合论文中的公式吧
![image](https://github.com/ziwei-jiang/PGGAN-PyTorch/assets/58846205/2b76e9db-5bf0-4f5c-bd8e-8efa5de519b0)
如果哪里有说明论文中公式错误，您方便的话，能否告知一下呢

**Comment by ziwei-jiang** [comment]
你好，感谢指出。这里应该是我implement时候出现疏忽。我会尽快fix这个问题。
