### ISSUE TITLE
RuntimeError: Given groups=1, weight of size [512, 513, 3, 3], expected input[1, 512, 257, 4] to have 513 channels, but got 512 channels instead

### ISSUE THREAD

**Issue by mingxingpu** [ziwei-jiang/PGGAN-PyTorch#4]
when I run command like :   python train.py --root ./root/ --epochs 40 --out_res 256 --cuda
I got this error 
![issue](https://github.com/ziwei-jiang/PGGAN-PyTorch/assets/59463530/cc3dfdd5-a8d0-4618-b376-2b28e0aba444)
how can I fix this error? pls.

**Comment by ziwei-jiang** [comment]
Hi,
I wasn't able to reproduce the error in the figure. Could you provide some more detail about your training setting?
